### ISSUE TITLE
Can the INO file

### ISSUE THREAD

**Issue by johnmholmes** [MartinDaCosta53/CBUSmINnOUT#11]
Gents
Can the .ino file be added to it own folder of the correct name and also include the  led library into this folder. after downloading the file and unzipping it, when you click on the file to load it into the Arduino Ide we get the warning which means the led files are then outside of the new folder.

![Screenshot 2024-01-12 221653](https://github.com/MartinDaCosta53/CANmINnOUT/assets/60571002/e796c0aa-bfd0-4771-93eb-dcd03eecf24c)

When you go to compile the sketch you get this error. easy to just copy over the files, but this could be fixed to stop this happening for beginners or less experience uses of Arduino Ide.

![Screenshot 2024-01-12 222155](https://github.com/MartinDaCosta53/CANmINnOUT/assets/60571002/bf25c4a4-160f-46af-8eed-fdd2e6569aaa)

**Comment by MartinDaCosta53** [comment]
John,

Do you mean like this?

 

https://github.com/MartinDaCosta53/CANmINnOUT

 

Martin

 

From: johnmholmes ***@***.***> 
Sent: Friday, January 12, 2024 10:25 PM
To: MartinDaCosta53/CANmINnOUT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MartinDaCosta53/CANmINnOUT] Can the INO file (Issue #11)

 

Gents
Can the .ino file be added to it own folder of the correct name and also include the led library into this folder. after downloading the file and unzipping it, when you click on the file to load it into the Arduino Ide we get the warning which means the led files are then outside of the new folder.

Screenshot.2024-01-12.221653.jpg (view on web) <https://github.com/MartinDaCosta53/CANmINnOUT/assets/60571002/e796c0aa-bfd0-4771-93eb-dcd03eecf24c> 

When you go to compile the sketch you get this error. easy to just copy over the files, but this could be fixed to stop this happening for beginners or less experience uses of Arduino Ide.

Screenshot.2024-01-12.222155.jpg (view on web) <https://github.com/MartinDaCosta53/CANmINnOUT/assets/60571002/bf25c4a4-160f-46af-8eed-fdd2e6569aaa>

**Comment by johnmholmes** [comment]
Hi Martin,
Yes That has fixed the issue I just download the project again and tested it in the Arduino Ide.
 
The issue can be closed on github.
 
John

**Comment by johnmholmes** [comment]
Closed the issue as fixed now
