### ISSUE TITLE
current warning

### ISSUE THREAD

**Issue by johnmholmes** [MartinDaCosta53/CBUSmINnOUT#12]
Gents should the warning to change to read something like this

"It is the users responsibility that the total current that the Arduino is asked to supply, stays within the capacity of the Arduino's chip. Failure to do this will result in terminal damage to your Arduino. "

Rather than

"Arduino is asked to supply stays within the capacity of the on board regulator."

**Comment by MartinDaCosta53** [comment]
Not agreed.  However, the warning has been expanded as follows:
"It is the users responsibility to ensure that the total current that the Arduino is asked to supply stays within the capacity of the on board regulator. The user should also ensure that the total pin out current source or sink stays within the maximum current rating of the Atmel processor. Failure to do this will result in terminal damage to your Arduino."
